name: Upload SVGs to main

on:
  schedule:
    - cron: '*/1 * * * *'  # Executa a cada 10 minutos
    
  workflow_dispatch:
  push:
    branches:
      - output
      
jobs:
  merge-svg-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Delete SVG files from main branch
        run: |
          find . -type f -name '*.svg' -delete
        working-directory: ${{ github.workspace }}

      - name: Checkout output branch
        uses: actions/checkout@v2
        with:
          ref: output

      - name: Merge SVG files from output branch
        run: |
          find . -type f -name '*.svg' -exec cp --parents {} ../main \;
        working-directory: ${{ github.workspace }}

      - name: Commit and push merged SVG files to main branch
        uses: EndBug/add-and-commit@v7
        with:
          message: "Merge SVG files from output branch to main branch"
          add: "main/*.svg"
          force: true
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
